### ISSUE TITLE
请问该如何运行lab5呢？

### ISSUE THREAD

**Issue by androny1012** [kazutoiris/MIT6.175#2]
已经用了镜像，有了connectal环境，但没有rv编译器，还是没能跑通lab5

**Comment by kazutoiris** [comment]
Now that you're aware that the reason for your mistake is the absence of a RISC-V compiler, it should be a straightforward fix. You can simply install a RISC-V compiler.

However, **please note that** my Docker image does not guarantee the inclusion of a RISC-V compiler or promote it as a standout feature.

`Pinpointing problems` is always the most challenging part, but now it's time to address and resolve the issue.
